### ISSUE TITLE
Non-hardcoded AES keys

### ISSUE THREAD

**Issue by bill-myers** [ogxd/gxhash#11]
The code seems to hardcode AES keys.

This makes no sense, and it should instead a mechanism similar to what the standard library uses to provide keys for SipHash.

**Comment by ogxd** [comment]
Hello @bill-myers,

As GxHash is a non-cryptographic algorithm, AES isn't used here for cryptography but for its excellent bit mixing properties, at a cheap computational cost via SIMD intrinsics. For this reason, there is no reason not to hardcode keys. SipHash is advertised as a "keyed hash function". GxHash isn't, it only is seeded, like many other non-cryptographic algorithms.

**Comment by ogxd** [comment]
Closing this issue. Feel free to create a new one with more information if you feel there I haven't covered your point with my answer
