### ISSUE TITLE
Clarification regarding hash stability

### ISSUE THREAD

**Issue by mahkoh** [ogxd/gxhash#110]
The description says that

>All generated hashes for a given version of GxHash are stable

By "given version", do you mean the major version, currently 3, or the patch version, currently 3.4.1.

I want to use gxhash in code generation but this requires the hashes to be the same for all semver-compatible versions of gxhash.

**Comment by ogxd** [comment]
Hello @mahkoh, they are stable for a given major version (eg using 3.2.4 or 3.4.1 it should return the same hash for a given input). If we were to make changes that alter values of generated hashes, we would bump the package to the next major version (eg version 4).   
I'll clarify this in the readme, thank you for your feedback.

**Comment by mahkoh** [comment]
Thanks for the quick reply!
