### ISSUE TITLE
Couple issues in the paper

### ISSUE THREAD

**Issue by magnusanderson-wk** [ogxd/gxhash#13]
Combiniting is not a word

"Ideally, half of the bit should change on average." should be "Ideally, half of the hash should change on average"

**Comment by ogxd** [comment]
Thanks for spotting this @magnusanderson-wk ! I have fixed it. Please let me know if you find other issues or things that could be better explained 😃

**Comment by ogxd** [comment]
Remarks were addressed, on top of others from https://github.com/ogxd/gxhash/pull/19
