### ISSUE TITLE
Functionality on stable

### ISSUE THREAD

**Issue by tgross35** [ogxd/gxhash#14]
It seems like this is nightly only, but it is probably pretty easy to get it working on stable. Here are some workarounds for the nightly features it uses:

- `pointer_byte_offsets`: just cast it back and forth `ptr.cast::<u8>().add(...).cast()` 
- `stmt_expr_attributes`: looks like you only use this to make `#[allow(unused_assignments)]` ok. You can probably eliminate this attribute and work around it with something like `let _tmp_ptr;` before the `if` block then `load_unaligned(_tmp_ptr, ...)`
- `core_intrinsics` for `likely`: you may be able to reverse this and get the same effects with stable [`#[cold]`](https://doc.rust-lang.org/reference/attributes/codegen.html#the-cold-attribute) instead. There is also [`likely_stable`](https://docs.rs/likely_stable/latest/likely_stable/fn.likely.html) which may work. You also might not even need it - not sure if you've benchmarked but iirc, `likely` doesn't gain as much in recent LLVM versions
- `stdsimd` for `_mm_loadu_epi8`. I'm unfortunately not really sure what to do here, maybe you could inline assembly it?

**Comment by tgross35** [comment]
Awesome project by the way!

**Comment by ogxd** [comment]
Thank you @tgross35 for your feedback and idea! Having it work on stable is definitely a must, I'll try to address this as soon as I can 😄

**Comment by ogxd** [comment]
Done :) 
'avx2' feature will require unstable toolchain however. I don't know if there is a way to have to work on the stable toolchain, but I think that can be addressed later.
I've added you as a contributor in case you want to review.

**Comment by ogxd** [comment]
It seems to also address another usability issue: I am under the impression that `stdsimd` required users to build with `target-cpu=native` otherwise performance would be degraded. Anyway it is much better without all these unstable features now, merging this and releasing. 
Thanks a lot!

**Comment by tgross35** [comment]
Glad to be of help! Another option is to add a Cargo feature called `nightly` and gate anything that needs it under `#[cfg(feature = "nightly)]`, with a fallback implementation under `#[cfg(not(feature = "nightly))]`. Then anyone who needs the highest performance can enable the feature, everyone else can live with the slightly slower stable version.

Thank you for the invitation, I accepted but don't know how I can help - I know about rust mechanics but not so much about the inner workings of hash algorithms. I suppose feel free to ping me if you need a hand figuring something out.
