### ISSUE TITLE
Latency benchmarks

### ISSUE THREAD

**Issue by GoldsteinE** [ogxd/gxhash#46]
Hi! It would be interesting to see comparison of time to hash a short string (like in [aHash] README). Throughput is great, but since in many cases hashmap keys are short strings, time to hash 40 KB of data is less relevant then time time to hash some e.g. 16-byte strings. Plot of hashing time per key size would be really helpful IMO. 

[aHash]: https://github.com/tkaitchuck/aHash

**Comment by ogxd** [comment]
Hi @GoldsteinE!

This is exactly what is shown in the benchmarks https://github.com/ogxd/gxhash?tab=readme-ov-file#benchmarks. 

What is displayed is throughput per input size. Throughput is just another way of viewing the performance. Throughput is in Gib/s, so if you want "latency". For instance, if we have a throughput of 8000 MiB/s for inputs of size 4 bytes, it means each 4 bytes hash takes 4 / 1014 / 1024 / 8000 s to compute or 4.8 nanoseconds.   

I prefer talking in terms of throughput but if you prefer timings per hash you already have everything you need (without having to compute it from throughput):
- The [throughput_criterion bench](https://github.com/ogxd/gxhash/blob/main/benches/throughput_criterion.rs) shows both throughput and timings per hash (or iteration if you prefer) for each input size. This bench uses the hash function directly, which does not know in advance about the input size.
- The [hashshet bench](https://github.com/ogxd/gxhash/blob/main/benches/hashset.rs) shows the timings per hash for several string size but also some integer types. Integers size is known in advance so the `Hash` can use fewer steps a thus is a little performant than using the hash function directly in that situation.

Fyi there are some heavy changes ongoing https://github.com/ogxd/gxhash/issues/34 https://github.com/ogxd/gxhash/issues/44 so for now I recommend taking benchmark results with a grain of salt.

**Comment by GoldsteinE** [comment]
HashSet bench looks interesting, thanks! What I meant is “benchmarks on the small inputs” (as far as I understand, benchmarks in readme are on 40KB inputs, which is a pretty rare case for a HashMap).

**Comment by ogxd** [comment]
> as far as I understand, benchmarks in readme are on 40KB inputs

No, the input size is on the X-axis. It ranges from 4 bytes to 32768 bytes.
<img width="617" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/079120af-a5cd-417a-8b51-5082b6efc7ad">

**Comment by GoldsteinE** [comment]
Oh, sorry then, I misread the plot. Thanks again!

**Comment by ogxd** [comment]
Np! Here is the same bench but tweaked to output time per hash (and with a log scaling on the Y axis). It is maybe closer to what you expected in the first place. These are the results for my MacBook pro M1

<img width="617" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/5439863e-08c4-494e-9544-8ade9a9efb89">

**Comment by chamoretto** [comment]
> Np! Here is the same bench but tweaked to output time per hash (and with a log scaling on the Y axis). It is maybe closer to what you expected in the first place. These are the results for my MacBook pro M1
> 
> <img alt="image" width="617" src="https://private-user-images.githubusercontent.com/12692438/292307190-5439863e-08c4-494e-9544-8ade9a9efb89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDI4MDksIm5iZiI6MTcwMzI0MjUwOSwicGF0aCI6Ii8xMjY5MjQzOC8yOTIzMDcxOTAtNTQzOTg2M2UtMDhjNC00OTRlLTk1NDQtOGFkZTlhOWVmYjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZjNiZDE4MjQ3Yzc4YTE2ZTYwODllMGI2MGNiNmQ3ZjFmMTBiMDUxNDlkNGFjM2YwMzQ4NGJhOGExZWZhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AtNdfYYM4fLAD3z4QxIwLm5HOGIAZ7XOzbGsGNmWpIw">

How did you get results under 1ns? At my intel 1235u i get results not lower then 500ns. Maybe we have different code changes?
My cnahges is just
`processor.on_result(len, throughput);` -> `processor.on_result(len, average_duration_s * 1_000_000_000.0);`
and enabling log scale at result_processor, but I get completely different numerical results and slightly different shapes of the curves.

![x86_64](https://github.com/ogxd/gxhash/assets/28485306/f342b742-ed1f-4d03-9b38-e33a1a7d9ebe)
![x86_64-avx2](https://github.com/ogxd/gxhash/assets/28485306/5082492a-3f38-4a5d-8ff8-0c7723aa56e9)
