### ISSUE TITLE
Feature request: add GxBuildHasher::with_seed

### ISSUE THREAD

**Issue by imartayan** [ogxd/gxhash#79]
I need a deterministic `BuildHasher` for my use case and I'd love to try gxhash.
Currently `GxHasher` has a `with_seed` constructor but not `GxBuildHasher`.
Would it be possible to add this?

Also, can you confirm that the hashes produced by gxhash are identical on all supported platforms when the seed is the same?

**Comment by imartayan** [comment]
I made a PR for this feature: https://github.com/ogxd/gxhash/pull/80

**Comment by ogxd** [comment]
Merged 👍
