### ISSUE TITLE
Cannot use cargo doc

### ISSUE THREAD

**Issue by blyxyas** [ogxd/gxhash#90]
I'm having some problems when using cargo doc having gxhash as a dependency. Setting RUSTFLAGS=... does not work :/ It still emits the "Gxhash requires aes and sse2 instrinsics..."

This does not happen with `cargo build`

**Comment by ogxd** [comment]
Hello @blyxyas, sorry for the delay. I tried to reproduce back when you opened this issue, but the problem would not arise on my laptop. I am leaving this issue open for later when I have more time to investigate and for visibility in case someone else is impacted. I'll keep you updated.

**Comment by ogxd** [comment]
Closing stale issue
